###
# Helix Editor config
###

# :config-open
# Linux and Mac: ~/.config/helix/config.toml
# Windows: %AppData%\helix\config.toml

# Theme list: https://helix-editor.vercel.app/reference/list-of-themes
theme = "dark_plus"

[editor]
line-number = "relative"

[editor.cursor-shape]
insert = "bar"

[editor.auto-save]
focus-lost = true

[editor.file-picker]
git-ignore = false

[keys.insert]
"C-s" = "normal_mode"
